<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.bitejiuyeke</groupId>
        <artifactId>zyh-house</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>zyh-common</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>zyh-common-core</module>
        <module>zyh-common-domain</module>
        <module>zyh-common-security</module>
        <module>zyh-common-redis</module>
        <module>zyh-common-cache</module>
        <module>zyh-common-rabbitmq</module>
        <module>zyh-common-message</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>